services:
  react-app:
    build: ../movies-app-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/movies-app-frontend
      - /movies-app-frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  express-app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/movies-app-backend
      - /movies-app-backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev